name: Deploy React Vite (Build CI)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/*"
          target: "/www/wwwroot/frontend_crm_live_chat/dist"

      - name: Restart PM2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            /www/server/nodejs/v24.15.0/bin/pm2 reload frontend_crm_live_chat || \
            /www/server/nodejs/v24.15.0/bin/pm2 start "npx serve -s dist -l 5173" --name frontend_crm_live_chat